language: node_js

sudo: required

node_js:
  - '8'

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8

before_install:
  - npm install -g npm@latest
  - npm install -g truffle

install:
  - npm install

script:
  - npm run test
